#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    background = 'transparent'
    template = "{{ if .SSHSession }} {{ end }}<green>{{if .Root }}<red>{{ end }}{{ .UserName }}"

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground = "white"
    template = "{{ if not .Root }}@{{ end }}"

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    background = 'transparent'
    foreground = "yellow"
    template = "{{ if not .Root }}{{ .HostName }}:{{ end }}"

  [[blocks.segments]]
    type = 'path'
    foreground = '#00acdf'
    template = ' {{ .Path }}'

    [blocks.segments.properties]
      style = 'agnoster_short'
      #style = 'powerlevel'
      max_depth = 3
      max_width = 4
      hide_root_location = true
      cycle = [ "#00acdf","#55d0ff","#7ce8ff","#ccf9ff" ]
      cycle_folder_separator = true

  [[blocks.segments]]
    type = "nix-shell"
    style = "plain"
    foreground = "magenta"
    background = "transparent"
    template = " (nix-{{ .Type }})"

#  [[blocks.segments]]
#    type = "docker"
#    style = "powerline"
#    powerline_symbol = ""
#    foreground = "#000000"
#    background = "#0B59E7"
#    template = "  {{ .Context }} "

  [[blocks.segments]]
    type = "terraform"
    style = "plain"
    foreground = "#ebcc34"
    background = "transparent"
    template = "{{.WorkspaceName}}"

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:grey'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

  [[blocks.segments]]
    type = "project"
    style = "plain"
    foreground = "#ffeb3b"
    background = "transparent"
    template = "{{ if .Error }}{{ .Error }}{{ else }}{{ if .Version }} {{.Version}}{{ end }} {{ if .Name }}{{ .Name }}{{ end }}{{ end }} "

  [[blocks.segments]]
    type = "python"
    style = "plain"
    foreground = "#906cff"
    background = "transparent"
    template = " {{ .Full }} "

  [[blocks.segments]]
    type = "lua"
    style = "powerline"
    powerline_symbol = ""
    foreground = "blue"
    background = "transparent"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    type = "go"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#7FD5EA"
    background = "transparent"
    template = "‭ﳑ {{ .Full }} "

  [[blocks.segments]]
    type = "aws"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#FFA400"
    background = "transparent"
    template = "  {{.Profile}}{{if .Region}}@{{.Region}}{{end}}"

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }} '

    [blocks.segments.properties]
      threshold = 5000

  [[blocks.segments]]
    type = "time"
    style = "plain"
    foreground = "#007ACC"
    template = '{{ .CurrentDate | date .Format }}'
    
    [blocks.segments.properties]
      time_format = "15:04:05"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}green{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}green{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯❯ '
